name: mathswithsd_admin
description: "MathsWithSD - AI-powered math exam platform for students and teachers."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # HTTP & Networking
  http: ^1.6.0
  
  # State Management
  provider: ^6.1.5+1
  
  # Storage
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^10.3.1
  
  # Image handling
  image_picker: ^1.2.2
  image_cropper: ^12.2.1
  image: ^4.8.0
  cached_network_image: ^3.4.1
  file_picker: ^12.0.0-beta.5
  
  
  # Camera
  camera: ^0.12.0+1
  permission_handler: ^12.0.1
  
  # Navigation
  go_router: ^17.3.0
  
  flutter_math_fork: ^0.7.2
  
  # Utils
  intl: ^0.20.2
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_avif: ^3.1.0

dependency_overrides:
  path_provider_android: 2.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
